### ISSUE TITLE
Corregir Doctest de gdb y gdbSpawmer

### ISSUE THREAD

**Issue by NicolasDiTomaso** [eldipa/ConcuDebug#104]
Gdb tuvo varias modificaciones en lo referente a que eventos lanza, principalmente debido al uso del plugin stdio redirect. Los test no fueron actualizados.

**Comment by NicolasDiTomaso** [comment]
Vengo a pedir un poco de ayuda...... corrigiendo el test de gdb llegue a un punto que falla el test.... pero no se por que. Aparentemente sucede al momento de llamar a gdb.exit() y me tira estos errores, que no me aportan nada:

    PROMPT$ python run.py gdb.rst 
    Run tests in PATH/test/gdb.rst
    ...................................................................................................................................................
    Traceback (most recent call last):
      File "py/doctestpyjs.py", line 261, in <module>
    sys.exit(doctest._test())

    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 138, in apport_excepthook
    

    Original exception was:
    Traceback (most recent call last):
      File "py/doctestpyjs.py", line 261, in <module>
        sys.exit(doctest._test())

    Exception KeyboardInterrupt in  ignored
    Traceback (most recent call last):
      File "/usr/lib/python2.7/atexit.py", line 13, in _run_exitfuncs
        def _run_exitfuncs():

    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 138, in apport_excepthook
        sys.__excepthook__(exc_type, exc_obj, exc_tb)

    Original exception was:
      File "/usr/lib/python2.7/atexit.py", line 13, in _run_exitfuncs
    def _run_exitfuncs():

    Generating wiki for PATH/test/gdb.rst
    Traceback (most recent call last):
      File "run.py", line 54, in <module>
        generate_wiki_pages(sources, wiki_directory)
      File "run.py", line 29, in generate_wiki_pages
        os.system("wikir %s > %s" % (source, page))
    Error in sys.excepthook:
    Traceback (most recent call last):
    Traceback (most recent call last):
      File "run.py", line 54, in <module>
        generate_wiki_pages(sources, wiki_directory)

    close failed in file object destructor:
    sys.excepthook is missing
    lost sys.stderr
    PROMPT$
 
Se menciona a atexit..... pero yo no lo estoy usando en ningun lado.... 
En el log lo unico raro que encontre fue esto (ademas de varios echos que antes no existian):

    For the topic '(the empty topic)' there are 0 callbacks.

    Exception in callback for the topic '(the empty topic)': Traceback (most recent call last):\n  File "PATH/src/py/publish_subscribe/eventHandler.py", line 223, in dispatch\n    callback(event[\'data\'])\n  File "<doctest gdb.rst[10]>", line 5, in add_sync\nNameError: global name \'shared_lock\' is not defined\n

shared_lock (mutex) es la misma variable que vengo usando en los test desde el comienzo de esto, y nunca me protesto.... es mas en este test se usa perfectamente varias veces... solo que al momento del "empty topic" que no estoy seguro por que se llama a un callback.... muere 

Alguna idea?

**Comment by eldipa** [comment]
Doctest puede estar agregando algun handler con atexit. Tambien hay un modulo para gdb en python que agrega algo a un atexit (pero este corren en el python de gdb).

No recuerdo otros contextos para atexit. Estas seguro que ese es el problema? Sobre que test falla (que parte de gdb.rst)?

**Comment by NicolasDiTomaso** [comment]
No, en este momento no estoy seguro que es lo que falla. Si bien el test no me dice donde falla (lo que sea que pasa, muere tan mal que mata al test), se que el error ocurre en gdb.exit(), cuando gdb fue attachado a algun proceso. Asi que de momento estoy investigando si hay algun problema con el revert del ioredirect.

Estoy intentando de correr el debugger de manera normal (con ui y todo), para ver si me tira algun error distinto. Pero por algun motivo me esta colgando en cualquier lado (en un step por ejemplo), lo que me preocupa mas... los logs no dicen que hubo ningun error, por pantalla no hay error.... simplemente no responde nunca mas...

**Comment by eldipa** [comment]
Tenes que encararlo exactamente al reves. Trata de reproducirlo sin la ui, sin el codigo python sin los plugins, etc. Recien luego vas agregando bloque a bloque hasta ver con cual nueva adicion todo pincha.

En algun otro test se hace gdb.exit()? Compararlo con otros tests puede ayudar tambien.

**Comment by NicolasDiTomaso** [comment]
Ok. Los test basicos de gdb y gdbSpawmer ya los consegui arreglar. El problema era (y posiblemente aun esta) en el plugin de stdioRedirect. Sin embargo el objetivo de los test es probar a gdb y no al plugin, asi que lo modifique para que funcione independientemente. Aun tengo el problema de que no me anda con la UI asi que ahora voy a revisar el redirect, probablemente al mismo tiempo que termine el tester de plugins.

Fijate de correr estos test: gdb1,2,3 y gdbSpawmer, a vos seguro te fallan (habiamos visto que gdb tiraba cosas distintas), pasame el resultado a ver si lo puedo generalizar un poco mas.

**Comment by eldipa** [comment]
Nop, a mi me andan perfecto todos los tests salvo gdb[2]. Ahora que tengo el mismo gdb que vos no pasa nada.

Este es el test que falla:
```
File "/home/martin/Codigo/ConcuDebug/test/gdb[2].rst", line 434, in gdb[2].rst
Failed example:
    shared_list #doctest: +NORMALIZE_WHITESPACE, +ELLIPSIS
Expected:
    [{u'stream': u'Quit\n', u'type': u'Log'},
      {u'klass': u'error',
       u'last_stream_records': [{u'stream': u'[Inferior 1 (process ...) exited normally]\n',
                                 u'type': u'Console'},
                                {u'stream': u'Quit\n', u'type': u'Log'}],
       u'results': {u'msg': u'Este programa no est\xe1 corriendo.'},
       u'token': None,
       u'type': u'Sync'},
      {u'klass': u'exit',
       u'last_stream_records': [],
       u'results': {},
       u'token': None,
       u'type': u'Sync'}]
Got:
    [{u'stream': u'Quit\n', u'type': u'Log'},
     {u'klass': u'error',
      u'last_stream_records': [{u'stream': u'[Inferior 1 (process 10620) exited normally]\n',
                                u'type': u'Console'},
                               {u'stream': u'Quit\n', u'type': u'Log'}],
      u'results': {u'msg': u'The program is not being run.'},
      u'token': None,
      u'type': u'Sync'}]
```

**Comment by eldipa** [comment]
alguna novedad?

**Comment by NicolasDiTomaso** [comment]
Perdon, no le di mucha bola a arreglar este test, por que basicamente es un problema de idioma, el test anda. de momento me preocupa mas que no consigo que funcione el stdioRedirect.
Ya arregle este test, probalo, si va todo bien cerra.

**Comment by eldipa** [comment]
Genial, todos los tests pasan. Cierro el ticket.

**Comment by NicolasDiTomaso** [comment]
Luego del commit ca8f49aadcd775081107e276eb7426b1fae4bce2 cambiaron los eventos lanzados, ya estan actualizados, por favor volve a probarlos, si anda, cerra.

**Comment by eldipa** [comment]
Funca todo de 10. Rapido y sin errores.
