### ISSUE TITLE
Enviar un EoF desde la UI al stdin

### ISSUE THREAD

**Issue by NicolasDiTomaso** [eldipa/ConcuDebug#89]
Ya que el stdin de un target esta redireccionada a traves de un fifo, en principio, hasta que dicho fifo no se cierre, el target no recibira un EoF.
El objetivo es poder enviar dicho EoF sin cerrar la redireccion (o cerrarla y reabrirla). Ademas, debe poder hacerse desde la ui, ya sea con un boton, o un tag especial

**Comment by NicolasDiTomaso** [comment]
Saco esto del milestone, aun no empece con la implementacion

**Comment by NicolasDiTomaso** [comment]
Dejo registrado aca, al igual que es en test que subi. Ya se puede enviar un eof al target via pid@EOF en el input de la ui. Sin embargo esto lo que hace es cerrar el fifo (lo que genera el eof) y luego volver a abrir (cosa de poder mantener la comunicacion) luego de un segundo. Si el target no realiza un read o alguna funcion que detecte dicho eof en esa ventana de tiempo, no lo va a detectar. Supongo que se podria matener cerrado al fifo y que el usuario pida reabrirlo?

**Comment by eldipa** [comment]
Creo que es mejor dejar cerrada la fifo. No veo un caso de uso en el cual un programa lea de stdin y que luego de cerrarse el  stdin, quiera seguir leyendo  (y esperar algo distinto de un error)

**Comment by NicolasDiTomaso** [comment]
Esto ya esta funcional, cierro, dejo la parte de ponerlo agradable a la vista en otro issue
